name: Merge Main to Docs Branch

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  sync-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main to docs branch
        run: |
          set -euo pipefail
          
          # 确保docs分支存在
          if ! git ls-remote --exit-code --heads origin docs > /dev/null 2>&1; then
            echo "Creating docs branch from main"
            git checkout -b docs
            git push origin docs
            exit 0
          fi
          
          # 切换到docs分支并合并main
          git fetch origin docs:docs
          git checkout docs
          git merge origin/main --no-ff -m "merge main to docs" || {
            echo "Merge conflict, resolving with main changes"
            git add -A
            git -c user.name="Docs Bot" -c user.email="docs@bot.com" commit -m "merge main to docs (resolved conflicts)"
          }
          
          git push origin docs