name: Merge Main to Docs Branch

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  sync-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main to docs branch
        run: |
          set -euo pipefail
          
          # 配置git用户
          git config user.name "Docs Bot"
          git config user.email "docs@bot.com"
          
          # 确保docs分支存在
          if ! git ls-remote --exit-code --heads origin docs > /dev/null 2>&1; then
            echo "Creating docs branch from main"
            git checkout -b docs
            git push origin docs
            exit 0
          fi
          
          # 切换到docs分支并合并main
          git fetch origin docs:docs
          git checkout docs
          git merge origin/main --no-ff -m "merge main to docs" || {
            echo "Merge conflict, resolving with main changes"
            git add -A
            git commit -m "merge main to docs (resolved conflicts)"
          }
          
          git push origin docs
          
      - name: Trigger navigation generation
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"subdocs-updated"}'